v0.6
Fixed help command
Fixed SUDOBIN config var being ignored
Added PACFLAGS and AURFLAGS config vars

diff --git a/papmw b/papmw
--- a/papmw
+++ b/papmw
@@ -5,12 +5,14 @@ if [[ -z "$@" ]]; then
 fi
 function getroot() {
     trap "true" SIGINT
-    sudo -k
-    if [ "$(sudo -- whoami)" != "root" ]; then echo "Superuser authentication failed."; exit 1; fi
+    if [ "$SUDOBIN" = "sudo" ] || [ "$SUDOBIN" = "/bin/sudo" ] || [ "$SUDOBIN" = "/usr/bin/sudo" ]; then sudo -k; fi
+    if [ "$($SUDOBIN whoami)" != "root" ]; then echo "Superuser authentication failed."; exit 1; fi
     trap - SIGINT
 }
 SUDOBIN="sudo"
 AURBIN="yay"
+PACFLAGS=""
+AURFLAGS=""
 IGNORE=""
 IGNOREGROUP=""
 function loadcfg() {
@@ -21,9 +23,10 @@ function loadcfg() {
         rm -f "$CFGFILENAME"
     fi
 }
+loadcfg "/etc/papmw.conf"
 loadcfg "${HOME}/.config/papmw.conf"
 loadcfg "${HOME}/.papmw.conf"
-PAPMWVER="0.5.1.1"
+PAPMWVER="0.6"
 PAC=""
 AUR=""
 NOTFOUND=""
@@ -32,13 +35,25 @@ shift
 case $COMMAND in
     "help" | "--help")
         if [ $# -gt 0 ]; then echo "Incorrect argument count."; exit 1; fi
-        echo "PAPMW - PQCraft's Arch Package Manager Wraper v$PAPMWVER"
+        echo "PAPMW - PQCraft's Arch Package Manager Wrapper v$PAPMWVER"
         echo "    Available commands:"
-        echo "        help/--help - displays this help text"
-        echo "        version/--version - displays the version and license info"
-        echo "        install PACKAGE... - installs packages"
-        echo "        uninstall/remove PACKAGE... - uninstalls packages"
-        echo "        refresh/sync - syncs repos"
+        echo "        help/--help                  - Displays this help text"
+        echo "        version/--version            - Displays the version and license info"
+        echo "        install PACKAGE...           - Installs packages"
+        echo "        uninstall/remove PACKAGE...  - Uninstalls packages"
+        echo "        refresh/sync                 - Syncs repos"
+        echo "        update/upgrade               - Upgrades packages"
+        echo "    Config variables:"
+        echo "        Configs are read from:"
+        echo "            /etc/papmw.conf"
+        echo "            ~/.config/papmw.conf"
+        echo "            ~/.papmw.conf"
+        echo "        SUDOBIN      - Path to executable to run commands as root"
+        echo "        AURBIN       - Path to the AUR helper"
+        echo "        PACFLAGS     - Options to pass to pacman"
+        echo "        AURFLAGS     - Options to pass to the AUR helper"
+        echo "        IGNORE       - Comma separated list of packages to ignore during upgrade"
+        echo "        IGNOREGROUP  - Comma separated list of package groups to ignore during upgrade"
         ;;
     "version" | "--version")
         if [ $# -gt 0 ]; then echo "Incorrect argument count."; exit 1; fi
@@ -51,10 +66,10 @@ case $COMMAND in
         p=0
         for i in "$@"; do
             printf "\r\e[0m\e[2K\e[1mSearching packages (%s%%)... [%s]\e[0m" "$((p*100/$#))" "$i"
-            if (pacman -Ss "^$i$" &> /dev/null); then 
+            if (pacman $PACFLAGS -Ss "^$i$" &> /dev/null); then 
                 PAC="$PAC$i "
             else
-                if [ "$("$AURBIN" -Ss "$i" 2> /dev/null | grep -E "*/$i ")" ]; then 
+                if [ "$("$AURBIN" $AURFLAGS -Ss "$i" 2> /dev/null | grep -E "*/$i ")" ]; then 
                     AUR="$AUR$i "
                 else
                     NOTFOUND="$NOTFOUND$i "
@@ -77,8 +92,8 @@ case $COMMAND in
             fi
         fi
         getroot
-        if [ "$PAC" ]; then sudo -- pacman --needed -S $PAC; fi
-        if [ "$AUR" ]; then "$AURBIN" --needed -S $AUR; fi
+        if [ "$PAC" ]; then $SUDOBIN -- pacman $PACFLAGS -S $PAC; fi
+        if [ "$AUR" ]; then "$AURBIN" $AURFLAGS -S $AUR; fi
         ;;
     "uninstall" | "remove")
         if [ $# -lt 1 ]; then echo "Incorrect argument count."; exit 1; fi
@@ -86,7 +101,7 @@ case $COMMAND in
         p=0
         for i in "$@"; do
             printf "\r\e[0m\e[2K\e[1mSearching packages (%s%%)... [%s]\e[0m" "$((p*100/$#))" "$i"
-            if (pacman -Q "$i" &> /dev/null); then 
+            if (pacman $PACFLAGS -Q "$i" &> /dev/null); then 
                 PAC="$PAC$i "
             else
                 NOTFOUND="$NOTFOUND$i "
@@ -110,13 +125,13 @@ case $COMMAND in
             fi
         fi
         getroot
-        sudo pacman -R $PAC
+        $SUDOBIN pacman $PACFLAGS -R $PAC
         ;;
     "refresh" | "sync")
         if [ $# -gt 0 ]; then echo "Incorrect argument count."; exit 1; fi
         getroot
         printf "\e[0m\e[1mRefreshing pacman...\e[0m\n"
-        sudo pacman -Sy
+        $SUDOBIN pacman $PACFLAGS -Sy
         printf "\e[0m\e[1mRefreshing AUR...\e[0m\n"
         yay -Sy
         ;;
@@ -125,7 +140,7 @@ case $COMMAND in
         getroot
         if [ "$IGNORE" ]; then IGNORE="--ignore=$(echo "$IGNORE" | sed 's/[ \t]*//g')"; fi
         if [ "$IGNOREGROUP" ]; then IGNOREGROUP="--ignoregroup=$(echo "$IGNOREGROUP" | sed 's/[ \t]*//g')"; fi
-        sudo pacman -Syu $IGNORE $IGNOREGROUP
+        $SUDOBIN pacman $PACFLAGS $IGNORE $IGNOREGROUP -Syu
         ;;
     *)
         echo "Unkown command:" "$COMMAND"
